mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: cn.yam.mcp.entity
server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mcp-test-db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

deepseek:
  api-key: ***REMOVED***

logging:
  level:
    root: INFO                # 全局日志级别
#    org.springframework: DEBUG # Spring 框架的日志
#    org.springframework.web: DEBUG # Spring Web 的日志
#    org.springframework.jdbc: DEBUG # Spring JDBC 的日志
